#!/usr/bin/env bash

install_path=$HOME/software/zig
prev_path=`pwd`
source_dir=`expr match $(readlink -f $0) '\(.*/sources\)'`"/zig"
llvm_path=$HOME/local/llvm18-release

echo "LLVM path: $llvm_path"
echo "zig source dir: $source_dir"
echo "zig installation dir: $install_path"

if [ -d $source_dir ]; then
    cd $source_dir
    git clean -dfx
    mkdir build
    cd build
    CMAKE_BUILD_PARALLEL_LEVEL=$(nproc) cmake .. \
                              -DCMAKE_PREFIX_PATH=$llvm_path \
                              -DCMAKE_BUILD_TYPE=Release

    make install
    rm -rf $install_path/*
    cp -r stage3/* $install_path/
    cd $prev_path
fi
